<?php 

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$model=$objectManager->create('Jimit\News\Model\Data');
$myTableData = $model->getCollection();

 echo "<table border=1><tr align=center><th>Title</th><th>Description</th></tr>";
    foreach ($myTableData->getData() as $data) {
        echo "<tr align=center>";
            echo "<td>".$data['data_title']."</td>";
            echo "<td>".$data['data_description']."</td>";
        echo "</tr>";
    }
    echo "</table>";
?>